# SPDX-FileCopyrightText: 2023 Julian-Samuel GebÃ¼hr
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure Owncast paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ owncast_uid }}"
    group: "{{ owncast_gid }}"
  with_items:
    - "{{ owncast_base_path }}"
    - "{{ owncast_data_path }}"

- name: Ensure Owncast support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ owncast_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ owncast_uid }}"
    group: "{{ owncast_gid }}"
  with_items:
    - env
    - labels

- name: Run if self-building of Owncast container image is not enabled
  when: "not owncast_container_image_self_build | bool"
  block:
    - name: Ensure Owncast container image is pulled via community.docker.docker_image
      when: sysd_docker_image_pull_method == 'ansible-module'
      community.docker.docker_image:
        name: "{{ owncast_container_image }}"
        source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
        force_source: "{{ owncast_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
        force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else owncast_container_image_force_pull }}"
      register: result
      retries: "{{ container_retry }}"
      delay: "{{ container_retry_delay }}"
      until: result is not failed

    - name: Ensure Owncast container image is pulled via ansible.builtin.command
      when: sysd_docker_image_pull_method == 'command'
      ansible.builtin.command:
        cmd: "{{ sysd_docker_host_command }} pull {{ owncast_container_image }}"
      register: result
      retries: "{{ container_retry }}"
      delay: "{{ container_retry_delay }}"
      until: result is not failed
      changed_when: "'Downloaded newer image' in result.stdout"

- name: Run if self-building of Owncast container image is enabled
  when: "owncast_container_image_self_build | bool"
  block:
    - name: Ensure Owncast repository is present on self-build
      ansible.builtin.git:
        repo: "{{ owncast_container_image_self_build_repo }}"
        version: "{{ owncast_container_image_self_build_repo_version }}"
        dest: "{{ owncast_container_image_self_build_src_files_path }}"
        force: "yes"
      register: owncast_git_pull_results

    - name: Ensure Owncast container image is built
      community.docker.docker_image:
        name: "{{ owncast_container_image_self_build_name }}"
        source: build
        force_source: "{{ owncast_git_pull_results.changed if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
        force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else owncast_git_pull_results.changed }}"
        build:
          dockerfile: Dockerfile
          path: "{{ owncast_container_image_self_build_src_files_path }}"
          pull: true
          args:

- name: Ensure Owncast container network is created via community.docker.docker_network
  when: sysd_docker_net_creation_method == 'ansible-module'
  community.docker.docker_network:
    enable_ipv6: "{{ sysd_docker_ipv6_enabled }}"
    name: "{{ owncast_container_network }}"
    driver: bridge
    driver_options: "{{ sysd_docker_net_driver_opts }}"

- name: Ensure Owncast container network is created via ansible.builtin.command
  when: sysd_docker_net_creation_method == 'command'
  ansible.builtin.command:
    cmd: >-
      {{ sysd_docker_host_command }} network create
      {% if sysd_docker_ipv6_enabled %}--ipv6{% endif %}
      {{ sysd_docker_net_driver_opts_string }}
      {{ owncast_container_network }}
  register: network_creation_result
  changed_when: network_creation_result.rc == 0
  failed_when: network_creation_result.rc != 0 and 'already exists' not in network_creation_result.stderr

- name: Ensure Owncast systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/okast.service.j2"
    dest: "{{ sysd_docker_service_path }}/{{ owncast_identifier }}.service"
    mode: "0644"
