# SPDX-FileCopyrightText: 2023 Julian-Samuel GebÃ¼hr
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Owncast systemd service
  ansible.builtin.stat:
    path: "{{ sysd_docker_path }}/{{ owncast_identifier }}.service"
  register: owncast_service_stat

- name: Uninstall Owncast systemd services and files
  when: owncast_service_stat.stat.exists | bool
  block:
    - name: Ensure Owncast systemd service is stopped
      ansible.builtin.service:
        name: "{{ owncast_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Owncast systemd service does not exist
      ansible.builtin.file:
        path: "{{ sysd_docker_path }}/{{ owncast_identifier }}.service"
        state: absent

    - name: Ensure Owncast container network does not exist via community.docker.docker_network
      when: sysd_docker_net_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ owncast_container_network }}"
        state: absent

    - name: Ensure Owncast container network does not exist via ansible.builtin.command
      when: sysd_docker_net_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ sysd_docker_host_command }} network rm
          {{ owncast_container_network }}
      register: network_deletion_result
      changed_when: owncast_container_network in network_deletion_result.stdout

    - name: Ensure Owncast path does not exist
      ansible.builtin.file:
        path: "{{ owncast_base_path }}"
        state: absent
